server.port=20029
server.boss-threads=1
server.worker-threads=16
server.connection-backlog=1024
server.max-requests-per-second=10000
server.max-frame-length=1048576
server.reader-idle-time=30
server.writer-idle-time=30
server.all-idle-time=60
server.connection-timeout=5000